package ollama

// TaskStep represents an individual unit of work generated by the 14B Planner.
type TaskStep struct {
	ID        string   `json:"id"`
	Command   string   `json:"command"`
	DependsOn []string `json:"depends_on"`
	Reason    string   `json:"reason"`
}

type MentalModelUpdates struct {
	NewQuirks []struct {
		ContextKey  string `json:"context_key"`
		Description string `json:"description"`
	} `json:"new_quirks"`
	ProfileUpdates []struct {
		Category  string `json:"category"`
		Attribute string `json:"attribute"`
		Value     string `json:"value"`
	} `json:"profile_updates"`
}

// PipelinePlan represents the collection of steps decoded from Ollama.
type PipelinePlan struct {
	Reasoning          string             `json:"reasoning,omitempty"`
	MentalModelUpdates MentalModelUpdates `json:"mental_model_updates,omitempty"`
	Steps              []TaskStep         `json:"steps"`
}

// OllamaOptions protects your VRAM from context explosion.
type OllamaOptions struct {
	NumCtx      int     `json:"num_ctx"`
	Temperature float64 `json:"temperature"`
}

// FormatSchema ensures the model respects structural constraints.
type FormatSchema struct {
	Type       string                 `json:"type"`
	Properties map[string]interface{} `json:"properties"`
	Required   []string               `json:"required"`
}

// EmbeddingRequest defines the payload structure sent to Ollama's embeddings endpoint.
type EmbeddingRequest struct {
	Model     string `json:"model"`
	Prompt    string `json:"prompt"`
	KeepAlive int    `json:"keep_alive"`
}

// EmbeddingResponse captures the float array vector returned by Ollama.
type EmbeddingResponse struct {
	Embedding []float32 `json:"embedding"`
}
